### ISSUE TITLE
Joi.when with schema test is not implemented

### ISSUE THREAD

**Issue by throrin19** [Twipped/joi-to-swagger#54]
Hello, I try to convert this Joi Schema to swagger but I have an error.

This is my schema : 

```js
Joi.when(Joi.object({ isCustom : true }).unknown(), {
    then        : Joi.object().keys(advancedAlert),
    otherwise   : Joi.object().keys(simpleAlert),
});
```

This is the error returned : 

```
Error: No schema was passed.
    at parse (project/node_modules/joi-to-swagger/index.js:19:21)
    at Object.alternatives (project/node_modules/joi-to-swagger/index.js:242:15)
    at parse (project/node_modules/joi-to-swagger/index.js:49:38)
    at children.forEach (project/node_modules/joi-to-swagger/index.js:296:15)
    at Array.forEach (<anonymous>)
    at Object.object (project/node_modules/joi-to-swagger/index.js:294:12)
    at parse (project/node_modules/joi-to-swagger/index.js:49:38)
```

**Comment by Mairu** [comment]
Joi.when support was added in version 4.0.0
